/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CpsKeyDetails {
        "name": string;
    }
    interface MyComponent {
        "colorFn"?: (a: string) => void;
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCpsKeyDetailsElement extends Components.CpsKeyDetails, HTMLStencilElement {
    }
    var HTMLCpsKeyDetailsElement: {
        prototype: HTMLCpsKeyDetailsElement;
        new (): HTMLCpsKeyDetailsElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cps-key-details": HTMLCpsKeyDetailsElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CpsKeyDetails {
        "name"?: string;
    }
    interface MyComponent {
        "colorFn"?: (a: string) => void;
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "cps-key-details": CpsKeyDetails;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cps-key-details": LocalJSX.CpsKeyDetails & JSXBase.HTMLAttributes<HTMLCpsKeyDetailsElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
